config/routes.rb
Rails.application.routes.draw do
  

  root 'static#index'

  get 'today' => 'static#today'

      resources :invoices do
        get 'download', on: :member
        resources :items
        resources :expenses
      end

      resources :matters
      resources :users

      get 'signup'  => 'users#new'
      

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	has_many :items, dependent: :destroy
	has_many :expenses, dependent: :destroy
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
	# http_basic_authenticate_with name: "Alex", password: "claudine10", except: [:index, :show]

	def index
		@invoices = Invoice.all
	end

	def show
		@invoice = Invoice.find(params[:id])
		@matters = Matter.all
		@items = Item.all
		@expenses = Expense.all
		@costs = 0
		@hours = 0
		
		# Total Expenses
		@expenses.each do |expense|
			if expense.invoice_id === @invoice.id
				@costs += expense.amount 
			end
		end

		# Total Amount Owed (Owed - Expenses) and Total Hours
		@items.each do |item|
			if item.invoice_id === @invoice.id
				@hours += item.hours
			end
		end

		@owed = (@hours * 40)

	end

	def new
		@invoice = Invoice.new
	end

	def edit
		@invoice = Invoice.find(params[:id])
	end

	def download
		@invoice = Invoice.find(params[:id])
	    @items = Item.all
		@expenses = Expense.all
	    @costs = 0
		@hours = 0
		
		# Total Expenses
		@expenses.each do |expense|
			if expense.invoice_id === @invoice.id
				@costs += expense.amount 
			end
		end

		# Total Amount Owed (Owed - Expenses) and Total Hours
		@items.each do |item|
			if item.invoice_id === @invoice.id
				@hours += item.hours
			end
		end

		@owed = (@hours * 40) + (@costs || 0)

		respond_to do |format|
	      format.html
	      format.pdf do
	          render :pdf => "Alex Hoover Invoice \##{@invoice.id} (#{@invoice.start_date.to_formatted_s(:long)} - #{@invoice.end_date.to_formatted_s(:long)})",
	                 :template => 'invoices/download.html.erb'
	        end
	    end


	end

	def create
		@invoice = Invoice.new(invoice_params)

		if @invoice.save 
			redirect_to @invoice
		else
			render 'new'
		end
	end

	def update
		@invoice = Invoice.find(params[:id])

		if @invoice.update(invoice_params)
			redirect_to @invoice
		else
			render 'edit'
		end
	end

	def destroy
		@invoice = Invoice.find(params[:id])
		@invoice.destroy

		redirect_to invoices_path
	end

	private
		def invoice_params
			params.require(:invoice).permit(:start_date, :end_date)
		end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<!-- Even though this form will be used in different context (new, edit), rails is smart enough to understand that @invoice should be used differently in teh different contexts. Normally, you would have to specify a different url and method for each context. -->
<%= form_for @invoice do |f| %>
  <% if @invoice.errors.any? %>
    <div id="errors-explanation">
      <h2>
        <% pluralize(@invoice.errors.count, "error") %>
        prohibited this article from being saved:
      </h2>
      <ul>
        <% @invoice.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :start_date %><br>
    <%= date_select :invoice, :start_date %>
  </p>

  <p>
    <%= f.label :end_date %><br>
    <%= date_select :invoice, :end_date %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/invoices/download.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "download" %>
    <%= stylesheet_link_tag "https://code.getmdl.io/1.1.1/material.indigo-pink.min.css" %>
  </head>
  <body>
    <div class="document">
	  <h1 class="title">Alex Hoover Invoice #<%= @invoice.id %></h1>
	  <p class="title">(<%= @invoice.start_date.to_formatted_s(:long) %> - <%= @invoice.end_date.to_formatted_s(:long) %>)</p>
	  <h2>
	  	Total Owed: <small><%= number_to_currency(@owed + @costs) %></small>
	  </h2>
	  <h2>
	  	Payments: <small><%= number_to_currency(@owed) %></small> | Expenses: <small><%= number_to_currency(@costs) %></small>
	  </h2>
	  <h2>Invoice for:</h2>
	  <address>
		<strong>Alex Hoover</strong><br>
		2861 29th St., NW<br>
		Apt. B<br>
		Washington, DC 20008<br>
	  </address>
	  <hr>
	  <h2>Items</h2>
	  <table class="table">
	  	<thead>
	  		<tr>
	  			<th>Date</th>
				<th>Matter</th>
				<th>Description</th>
				<th>Hours</th>
				<th></th>
	  		</tr>
	  	</thead>
	  	<tbody>
	  		<%= render @invoice.items.order(date: :asc) %>
	  		<tr>
	  			<td colspan="2"></td>
	  			<td><b>Total Hours</b></td>
	  			<td><%= @hours %></td>
	  		</tr>
	  		<tr>
	  			<td colspan="2"></td>
	  			<td><b>Rate</b></td>
	  			<td>$40</td>
	  		</tr>
	  		<tr>
	  			<td colspan="2"></td>
	  			<td><b>Amount Owed</b></td>
	  			<td><%= number_to_currency(@owed) %></td>
	  		</tr>

	  	</tbody>
	  </table>
	  <h2>Expenses</h2>
	  <table class="table">
	  	<thead>
	  		<tr>
				<th>Matter</th>
				<th>Description</th>
				<th>Amount</th>
				<th></th>
	  		</tr>
	  	</thead>
	  	<tbody>
	  		<%= render @invoice.expenses %>
	  		<tr>
	  			<td></td>
	  			<td><b>Total Expenses</b></td>
	  			<td><%= number_to_currency(@costs) %></td>
	  		</tr>
	  	</tbody>
	  </table>
	</div>
  </body>
</html>

app/views/invoices/edit.html.erb
<h1>Edit Invoice</h1>

<%= render 'form' %>

<!-- Link back to the list of invoices -->
<%= link_to 'All Invoices', invoices_path %>

app/views/invoices/index.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--12-col mdl-cell--12-col-phone">
    <h1>Invoices</h1>
    <table class="mdl-data-table mdl-js-data-table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Start Date</th>
          <th>End Date</th>
          <th class="mdl-data-table__cell--non-numeric"></th>
          <th class="mdl-data-table__cell--non-numeric"></th>
          <th class="mdl-data-table__cell--non-numeric"></th>
        </tr>
      </thead>
      <tbody>
        <% @invoices.each do |invoice| %>
          <tr>
            <td><%= invoice.id %></td>
            <td><%= invoice.start_date.to_formatted_s(:long) %></td>
            <td><%= invoice.end_date.to_formatted_s(:long) %></td>
            <td><%= link_to 'View', invoice_path(invoice) %></td>
            <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
            <td>
              <%= link_to 'Delete', invoice_path(invoice),
                method: :delete,
                data: {confirm: "Are you sure?"} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <p></p>
    <%= link_to 'New Invoice', new_invoice_path, class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" %>
  </div>
</div>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form' %>

<%= link_to 'All Invoices', invoices_path %>

app/views/invoices/show.html.erb
<div class="mdl-grid">
	<div class="mdl-cell mdl-cell--8-col">
		<h2>Invoice #<%= @invoice.id %></h2>
		<div class="mdl-card__subtitle-text">
			<%= @invoice.start_date.to_formatted_s(:long) %> - <%= @invoice.end_date.to_formatted_s(:long) %> <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_invoice_path(@invoice) %>
		</div>
	</div>
	<div class="mdl-cell mdl-cell--4-col">
		<%= render "shared/stats" %>
		<%= button_to 'Download Invoice', download_invoice_path(@invoice, :format => :pdf), class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent full-width" %>
	</div>
</div>

<div class="mdl-grid">
	<div class="mdl-cell mdl-cell--12-col mdl-cell--12-col-phone">
		<h4>Payments</h4>
		<%= render "items/form" %>
		<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp full-width">
			<thead>
				<tr>
					<th class="mdl-data-table__cell--non-numeric">Date</th>
					<th class="mdl-data-table__cell--non-numeric">Matter</th>
					<th class="mdl-data-table__cell--non-numeric full-width">Description</th>
					<th class="mdl-data-table__cell">Hours</th>
					<th class="mdl-data-table__cell"></th>
				</tr>
			</thead>
			<tbody>
				<!-- This calls the _item partial -->
				<%= render @invoice.items.order(date: :desc) %>	
			</tbody>
		</table>
	</div>
</div>
<div class="mdl-grid">
	<div class="mdl-cell mdl-cell--12-col mdl-cell--12-col-phone">
		<h4>Expenses</h4>
		<%= render "expenses/form" %>
		<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp full-width">
			<thead>
				<tr>
					<th class="mdl-data-table__cell--non-numeric">Matter</th>
					<th class="mdl-data-table__cell--non-numeric">Description</th>
					<th class="mdl-data-table__cell">Amount</th>
					<th class="mdl-data-table__cell"></th>
				</tr>
			</thead>
			<tbody>
				<!-- This calls the _expense partial -->
				<%= render @invoice.expenses %>	
			</tbody>
		</table>
	</div>
</div>
<div class="mdl-grid">
	
</div>