config/routes.rb
Rails.application.routes.draw do
  

  root 'static#index'

  get 'today' => 'static#today'

      resources :invoices do
        get 'download', on: :member
        resources :items
        resources :expenses
      end

      resources :matters
      resources :users

      get 'signup'  => 'users#new'
      

end

app/models/matter.rb
class Matter < ActiveRecord::Base
	has_many :items
	has_many :expenses

	validates :name, presence: true
end

app/controllers/matters_controller.rb
class MattersController < ApplicationController
	def index
		@matters = Matter.all
		@matter = Matter.new
	end

	def new
		@matter = Matter.new
	end

	def edit
		@matter = Matter.find(params[:id])
	end

	def create
		@matter = Matter.new(matter_params)
		@matter.save

		if @matter.save
			redirect_to action: "index"
		else
			render 'new'
		end
	end

	def update
		@matter = Matter.find(params[:id])

		if @matter.update(matter_params)
			redirect_to  action: "index"
		else
			render 'edit'
		end
	end

	def destroy
		@matter = Matter.find(params[:id])
		@matter.destroy

		redirect_to matters_path
	end

	private
		def matter_params
			params.require(:matter).permit(:name)
		end
end

app/helpers/matters_helper.rb
module MattersHelper
end

app/views/matters/_form.html.erb
<%= form_for @matter do |f| %>
  <% if @matter.errors.any? %>
    <div id="errors-explanation">
      <h2>
        <% pluralize(@matter.errors.count, "error") %>
        prohibited this article from being saved:
      </h2>
      <ul>
        <% @matter.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/matters/edit.html.erb
<h1>Edit Matter</h1>
<hr>
<%= render 'form' %>

app/views/matters/index.html.erb
<div class="mdl-grid">
	<div class="mdl-cell mdl-cell--12-col">
		<h1>Matters</h1>
		<%= form_for @matter do |f| %>
		    <div class="mdl-textfield mdl-js-textfield">
		    	<%= f.label :name, class: "mdl-textfield__label" %>
		    	<%= f.text_field :name, class: "mdl-textfield__input" %>
		    </div>
		    <%= f.submit "Add", class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" %>
		<% end %>
		<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
			<thead>
				<tr>
					<th>Id</th>
					<th class="mdl-data-table__cell--non-numeric">Name</th>
					<th class="mdl-data-table__cell"></th>
					<th class="mdl-data-table__cell"></th>
				</tr>
			</thead>
			<tbody>
				<% @matters.each do |matter| %>
					<tr>
						<td class="mdl-data-table__cell"><%= matter.id %></td>
						<td class="mdl-data-table__cell--non-numeric"><%= matter.name %></td>
						<td class="mdl-data-table__cell--non-numeric"><%= link_to "Edit", edit_matter_path(matter) %></td>
						<td class="mdl-data-table__cell--non-numeric">
							<%= link_to 'Delete', matter_path(matter),
							  method: :delete,
							  data: {confirm: "Are you sure?"} %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/matters/new.html.erb
<h1>New Matter</h1>
<hr>
<%= render 'form' %>