config/routes.rb
Rails.application.routes.draw do
  

  root 'static#index'

  get 'today' => 'static#today'

      resources :invoices do
        get 'download', on: :member
        resources :items
        resources :expenses
      end

      resources :matters
      resources :users

      get 'signup'  => 'users#new'
      

end

app/views/layouts/_header.html.erb
<!-- Header. Like "navbar" -->
<header class="mdl-layout__header">
	<!-- Icon -->
	<div class="mdl-layout-icon"></div>
	<!-- A row in the header. MDL supports multiple rows in the header -->
	<div class="mdl-layout__header-row">
		<!-- Title. Like "navbar-brand" -->
		<span class="mdl-layout-title">Invoices</span>
	</div>
</header>

app/views/layouts/_sidebar.html.erb
<div class="mdl-layout__drawer">
	<span class="mdl-layout-title">Invoices</span>
	<nav class="mdl-navigation">
		<%= link_to "Home", root_path, class: "mdl-navigation__link" %>
		<%= link_to "Today", {controller: "static", action: "today"}, class: "mdl-navigation__link" %>
		<%= link_to 'New Invoice', new_invoice_path, class: "mdl-navigation__link" %>
		<%= link_to "Invoices", invoices_path, class: "mdl-navigation__link" %>
		<%= link_to "Matters", matters_path, class: "mdl-navigation__link" %>
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Invoices</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>
	<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
		<%= render 'layouts/header' %>
		<%= render 'layouts/sidebar' %>
		<main class="mdl-layout__content">
			<%= render 'shared/flash' %>
			<%= yield %>
		</main>
	</div>
</body>
</html>